#!/bin/bash
#SBATCH --gres=gpu:1
#SBATCH --gres-flags=enforce-binding
#SBATCH -c 8
#SBATCH --mem-per-cpu=8GB
#SBATCH -C gpu32
#SBATCH --time=3-00:00:00
#SBATCH --job-name="VRDATTN"
#SBATCH -o slurm-VRDATTN-%j.%N.out
#SBATCH --mail-user=kjain@knights.ucf.edu
#SBATCH --mail-type=END,FAIL
##SBATCH --requeue
echo CUDA_VISIBLE_DEVICES=$CUDA_VISIBLE_DEVICES
nvidia-smi
VRAM=`nvidia-smi --query-gpu=memory.total --format=csv | head -2 | tail -1 | awk '{print $1}'`
echo $VRAM
python --version
python train.py
nvidia-smi